description: "Supply creation on a Space"
baseURL: "http://localhost:8080/api"
actions:
  - endpoint: "space"
    method: "POST"
    statusCode: 201
    body:
      space_name: "TEST SPACE"
      role: 0
    setters:
      space_id: "space_id"
    logRequestBody: true
    logResponseBody: true
  - endpoint: "space/@{space_id}/measure_unit"
    method: "POST"
    statusCode: 201
    body:
      description: "METER"
      abbreviation: "m"
      type: 1
      used_in_unit_cost: true
      used_in_general_expenses: true
      allowed_supply_types: "1"
    setters:
      measure_unit_id: "measure_unit_id"
  - endpoint: "space/@{space_id}/supply"
    method: "POST"
    statusCode: 201
    body:
      measure_unit_id: "@{measure_unit_id}"
      measure_unit_purchase_id: "@{measure_unit_id}"
      supply_type: 0
      description: "SUPPLY A"
      specifications: ""
      price: 3.34
    logRequestBody: true
    logResponseBody: true
  - endpoint: "space/@{space_id}"
    method: "DELETE"

